language:
- clojure
- node_js
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - client/node_modules
sudo: required
services:
- docker
before_install:
- cd keycloak
- ./server.sh build && ./server.sh run
- cd ..
- cd client
- nvm install 4
- npm config set spin false
- npm install
- cd ../backend
- cp profiles.clj.template profiles.clj
- ./provision/setup.sh
- mkdir -p $HOME/.lein
- echo '{:user {:plugins [[jonase/eastwood "0.2.3"]]}}' > $HOME/.lein/profiles.clj
script:
- lein do clean, check, test :all, eastwood '{:source-paths ["src" "test"]}'
- cd ../client
- npm run lint
- npm test
notifications:
  slack:
    secure: iO7fj8eFN5wyYSwwmlG4h5vVAWFVgKyH6o3uBq1kSrBbFlCPNQlBd92AeG3emf6DGR25cX0yRfmSQfQoIV1q//iJNyoMTVEG80Cw2aTjrp2IJ2u9ZkBVmDREILJEgj/qA6RRsYOoYsqTVGwLmkFyXBlTUL6GB4ZMPriyHgjjJOwTuJ1vhKoz7WIOeFCyMssNY6SNkfiZT1OFAoqmSlsP3B/W/tRtJT831mEApHcJ6QzBjsRnDwlB5P42tB1OlANTflfdpcIHkPQy/LeRxj9HorctkGiR4B0wExClfPHJQNldtzxUbgI9lpseiuAEUaqgQIRmpP6vXgOCGE8gzIoVWN3ZQgAxdCbvK/31lI2fIjPOLMUfC3BqQw9KI2lG5nH0rN1/YE5mgKM2GlQHX5URViLFQzpTyulZ/Mxh+LsaPScEyz+nFDZpaNuGx/o7dKv5FkVCj2gWRLgyJuSEKFFZtDMcsn24++uOe1eBEWsciJp51HiHeJCOFiEJnWrmhglwdsrgfGjqChsQFv28TVdcJoyO6WY7kDKrso+Xw+kOMffqGHnI/w856nEQCmGY+sR8oiEd+eDn3s4v5kwuWZ2P0gzro+8zH45AFh0OHVht4Nj0PTVy6oaK20UvcBhvAaV0ZpBBM8NhvYqNPI50Wua5asTAEbqo3GGJuQXS2zPg5b4=
