version: "3"
services:
 backend:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-backend:${CI_COMMIT}"
   environment:
     - WAIT_FOR_DEPS=true
     - LUMEN_DB_URL=jdbc:postgresql://postgres/lumen?user=lumen&password=password&ssl=true
     - CI_BUILD=yes
     - LUMEN_FILE_UPLOAD_PATH=/tmp/akvo/lumen
     - LUMEN_AUTH_URL=http://auth.lumen.local:8080/auth/realms/akvo
     - LUMEN_AUTH_PUBLIC_CLIENT_ID=akvo-lumen
     - LUMEN_AUTH_RSA_SUFFIX_URL=/protocol/openid-connect/certs
     - LUMEN_KEYCLOAK_URL=http://auth.lumen.local:8080/auth
     - LUMEN_KEYCLOAK_CLIENT_SECRET=caed3964-09dd-4752-b0bb-22c8e8ffd631
     - LUMEN_ENCRYPTION_KEY=secret
     - LUMEN_SENTRY_BACKEND_DSN=https://xxxx@sentry.io/111111
     - LUMEN_SENTRY_CLIENT_DSN=https://xxxx@sentry.io/111111
     - LUMEN_SENTRY_BACKEND_DSN=${LUMEN_SENTRY_BACKEND_DSN}
     - LUMEN_EMAIL_USER=admin@akvo.org
     - LUMEN_EMAIL_PASSWORD=password
     - LUMEN_FLOW_API_URL=flow-url
     - LUMEN_PIWIK_SITE_ID=165
     - LUMEN_DEPLOYMENT_COLOR=${CI_BRANCH}
     - LUMEN_DEPLOYMENT_ENVIRONMENT=${USER}
     - LUMEN_DEPLOYMENT_VERSION=${CI_COMMIT}
 client:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-client:${CI_COMMIT}"
   expose:
      - 80
   depends_on:
     - backend
     - windshaft
   command: >
      sh -c "sed -i /etc/nginx/conf.d/default.conf -e 's/localhost:3000/backend:3000/' -e 's/localhost:4000/windshaft:4000/' && nginx -g 'daemon off;'"
 redis:
 windshaft:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-maps:${CI_COMMIT}"

 backend-functional-tests:
   image: akvo/akvo-lumen-backend-dev:20191001.144150.7c1e95e
   environment:
     - PGSSLMODE=require
     - PGSSLROOTCERT=/pg-certs/server.crt
     - PGPASSWORD=password # password of lumen role
   volumes:
      - pg-data:/pg-certs:ro
      - ./backend:/app
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/home/akvo/.lein
   links:
      - keycloak:auth.lumen.local
   command: "true"
 fe-e2e-tests:
   environment:
      - LUMEN_URL=http://t1.lumen.local/
 exporter:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-exporter:${CI_COMMIT}"
