apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lumen-blue-green-gateway
spec:
  template:
    metadata:
      labels:
        run: lumen-blue-green-gateway        
    spec:
      containers:
      - image: rosskukulinski/nginx-kubernetes-reload:v2.0.1
        imagePullPolicy: Always
        name: gateway
        resources:
          requests:
            cpu: "50m"            
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        env:
          - name: WATCH_PATHS
            value: "/etc/nginx /etc/nginx/conf.d"
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: lumen-blue-green-config
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: lumen-blue-green-config
        configMap:
          name: lumen-blue-green-config
---
apiVersion: v1
data:
  default.conf: |-
        client_max_body_size 50M;
        large_client_header_buffers 16 32k;

        gzip on;
        gzip_comp_level    5;
        gzip_min_length    256;
        gzip_proxied       any;
        gzip_vary          on;
        gzip_types
            application/javascript
            application/json
            application/x-font-ttf
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/css
            text/plain
            text/html;

        log_format upstream_time '$remote_addr - $remote_user [$time_local] "$request_method"'
                                     ' $status $body_bytes_sent '
                                     '"$http_referer" "$http_user_agent"'
                                     'rt=$request_time urt="$upstream_response_time"';
        server {
            listen       80 default_server;

            access_log  /var/log/nginx/access.log  upstream_time;

            location / {
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-Host $host;
                proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_set_header    X-Blue-Green-State 'live';
                proxy_pass          http://lumen-live;
            }

        }

        server {
            listen       80;
            server_name  ~^dark-.+$;

            access_log  /var/log/nginx/access.log  upstream_time;

            location / {
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-Host $host;
                proxy_set_header    X-Blue-Green-State 'dark';
                proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_pass          http://lumen-dark;
            }
        }
kind: ConfigMap
metadata:
  name: lumen-blue-green-config
